-- filters { "configuration:Debug;platforms:x64" }
-- 	architecture "x86_64"
-- 	flags { "Unicode" }
-- 	defines { "GLEW_STATIC", "WIN32" }
-- 	defines { "WIN32", "_LIB" }
-- 	defines { "DEBUG", "_DEBUG", "_DEBUG_", "Debug" }
-- 	flags { "Symbols" }
-- 	optimize "Debug"

-- filters { "configuration:Release;platforms:Win32" }
-- 	architecture "x86"
-- 	flags { "Unicode" }
-- 	defines { "GLEW_STATIC", "WIN32" }
-- 	defines { "WIN32", "_LIB" }
-- 	defines { "NDEBUG", "NDebug" }
-- 	flags { "Optimize", "NoBoundsCheck" }
-- 	optimize "Full"

-- filters { "configuration:Release;platforms:x64" }
-- 	architecture "x86_64"
-- 	flags { "Unicode" }
-- 	defines { "GLEW_STATIC", "WIN32" }
-- 	defines { "WIN32", "_LIB" }
-- 	defines { "NDEBUG", "NDebug" }
-- 	flags { "Optimize", "NoBoundsCheck" }
-- 	optimize "Full"